#pragma once

#include "lang/lang_keys.h"
#include <QtCore/QString>
#include <QtCore/QMap>

namespace {

  inline QString AyuHantHelper(const QString &key, const QString &fallback) {
    static const QMap<QString, QString> dict = {
      // Ayu Settings
      {"ayu_GhostEssentialsHeader", "幽靈模式（隱私）"},
      {"ayu_DontReadMessages", "讀取訊息不標示已讀"},
      {"ayu_DontReadStories", "觀看限時動態不標示已讀"},
      {"ayu_DontSendOnlinePackets", "不顯示上線狀態"},
      {"ayu_DontSendUploadProgress", "不顯示打字中/傳送中"},
      {"ayu_SendOfflinePacketAfterOnline", "上線後立即顯示離線"},
      {"ayu_GhostModeToggle", "幽靈模式選項"},
      {"ayu_MarkReadAfterAction", "互動後自動標記已讀"},
      {"ayu_MarkReadAfterActionDescription", "當你發送訊息或貼圖回應後，自動將該對話標記為已讀。"},
      {"ayu_UseScheduledMessages", "使用排程訊息"},
      {"ayu_UseScheduledMessagesDescription", "送出的訊息會改為排程發送（預設延遲 12 秒），可降低上線暴露。網路不穩時不建議啟用。"},
      {"ayu_SendWithoutSoundByDefault", "啟用無聲發送"},
      {"ayu_SendWithoutSoundByDefaultDescription", "預設以無聲方式送出訊息。"},
      {"ayu_SpyEssentialsHeader", "訊息留存"},
      {"ayu_SaveDeletedMessages", "保留被刪除的訊息"},
      {"ayu_SaveMessagesHistory", "保留訊息編輯紀錄"},
      {"ayu_MessageSavingSaveForBots", "也在BOT私訊時啟用防刪除"},
      {"ayu_MessageSavingExcludeBotsInGroups", "不阻擋群組中的BOT刪除訊息"},
      {"ayu_MessageSavingOtherHeader", "其他功能"},
      {"ayu_LocalPremium", "解鎖本機 Premium (僅限非伺服器端限制)"},
      {"ayu_DisableAds", "隱藏贊助/廣告內容"},
      {"ayu_ImproveDC5Connection", "啟用 DC5 連線優化（實驗性）"},

      // General Settings
      {"ayu_CategoryGeneral", "一般設定"},
      {"ayu_TranslationProvider", "翻譯服務提供者"},
      {"ayu_SettingsShowID", "資料頁顯示 ID 根據"},
      {"ayu_SettingsShowID_Hide", "隱藏"},
      {"ayu_SettingsShowMessageID", "顯示訊息 ID"},
      {"ayu_SettingsShowViewJson", "右鍵顯示 [查看 JSON] 選項"},
      {"ayu_DisableStories", "停用限時動態"},
      {"ayu_DisableOpenLinkWarning", "停用外部連結警告"},
      {"ayu_DisableSimilarChannels", "停用相似頻道推薦"},
      {"ayu_CollapseSimilarChannels", "摺疊相似頻道"},
      {"ayu_HideSimilarChannelsTab", "隱藏相似頻道分頁"},
      {"ayu_DisableNotificationsDelay", "停用通知延遲"},
      {"ayu_SettingsShowMessageSeconds", "在訊息時間中顯示秒數"},
      {"ayu_SettingsSpoofWebviewAsAndroid", "將 Webview 模擬為 Android 裝置"},
      {"ayu_SettingsBiggerWindow", "加大 Webview 視窗"},
      {"ayu_SettingsIncreaseWebviewHeight", "增加高度"},
      {"ayu_SettingsIncreaseWebviewWidth", "增加寬度"},
      {"ayu_ConfirmationsTitle", "操作確認"},
      {"ayu_StickerConfirmation", "發送貼圖前確認"},
      {"ayu_GIFConfirmation", "發送 GIF 前確認"},
      {"ayu_VoiceConfirmation", "發送語音訊息前確認"},

      // Appearance Settings
      {"ayu_CategoryAppearance", "外觀設定"},
      {"ayu_AppIconHeader", "應用程式圖示"},
      {"ayu_HideNotificationBadge", "隱藏通知標記"},
      {"ayu_HideNotificationBadgeDescription", "隱藏工作列圖示上的未讀計數標記。"},
      {"ayu_MaterialSwitches", "使用 Material Design 風格開關"},
      {"ayu_RemoveMessageTail", "移除對話氣泡尾巴"},
      {"ayu_DisableCustomBackgrounds", "停用自訂對話背景"},
      {"ayu_MonospaceFont", "等寬字型"},
      {"ayu_FontDefault", "系統預設"},
      {"ayu_ChatFoldersHeader", "對話分頁設定"},
      {"ayu_HideNotificationCounters", "隱藏通知計數"},
      {"ayu_HideAllChats", "隱藏「所有對話」分頁"},
      {"ayu_DrawerElementsHeader", "側選單項目"},
      {"ayu_LReadMessages", "本機標記已讀 (不影響伺服器)"},
      {"ayu_SReadMessages", "伺服器同步已讀"},
      {"ayu_StreamerModeToggle", "防擷取模式"},
      {"ayu_TrayElementsHeader", "系統匣項目"},
      {"ayu_EnableGhostModeTray", "在系統匣顯示幽靈模式開關"},
      {"ayu_EnableStreamerModeTray", "啟用防擷取模式"},
      {"ayu_DisableStreamerModeTray", "停用防擷取模式"},

      // Chats Settings
      {"ayu_CategoryChats", "對話設定"},
      {"ayu_ShowOnlyAddedEmojisAndStickers", "僅顯示已新增的表情符號與貼圖"},
      {"ayu_HideReactions", "隱藏回應反應 (Reactions)"},
      {"ayu_HideReactionsInChannels", "在頻道中隱藏"},
      {"ayu_HideReactionsInGroups", "在群組中隱藏"},
      {"ayu_SettingsRecentStickersCount", "常用貼圖顯示數量"},
      {"ayu_ChannelBottomButton", "頻道底部按鈕行為"},
      {"ayu_ChannelBottomButtonHide", "隱藏"},
      {"ayu_ChannelBottomButtonMute", "靜音 / 取消靜音"},
      {"ayu_ChannelBottomButtonDiscuss", "前往討論群組"},
      {"ayu_QuickAdminShortcuts", "管理員快速操作捷徑"},
      {"ayu_SettingsShowMessageShot", "顯示「訊息截圖」按鈕"},
      {"ayu_SettingsShowMessageShotDescription", "在訊息操作選單中加入截圖功能。"},
      {"ayu_MessageShotTopBarText", "訊息截圖"},
      {"ayu_MessageShotPreview", "預覽"},
      {"ayu_MessageShotPreferences", "偏好設定"},
      {"ayu_MessageShotCopy", "複製"},
      {"ayu_MessageShotSave", "儲存"},
      {"ayu_MessageShotTheme", "主題"},
      {"ayu_MessageShotThemeDefault", "預設值"},
      {"ayu_MessageShotThemeSelectTitle", "選擇訊息主題"},
      {"ayu_MessageShotThemeApply", "套用"},
      {"ayu_MessageShotShowBackground", "顯示背景"},
      {"ayu_MessageShotShowDate", "顯示日期"},
      {"ayu_MessageShotShowReactions", "顯示反應"},
      {"ayu_MessageShotShowColorfulReplies", "顯示彩色回覆"},
      {"ayu_DeletedMarkText", "已刪除訊息標記文字"},
      {"ayu_EditedMarkText", "已編輯訊息標記文字"},
      {"ayu_ReplaceMarksWithIcons", "將標記替換為圖示"},
      {"ayu_HideShareButton", "隱藏快速分享按鈕"},
      {"ayu_SimpleQuotesAndReplies", "簡約引用與回覆風格"},
      {"ayu_SettingsWideMultiplier", "對話寬度比例"},
      {"ayu_SettingsWideMultiplierDescription", "調整對話氣泡的最大寬度比例。修改後需重啟程式。"},
      {"ayu_ContextMenuElementsHeader", "右鍵選單項目"},
      {"ayu_SettingsContextMenuItemHidden", "隱藏"},
      {"ayu_SettingsContextMenuItemShown", "顯示"},
      {"ayu_SettingsContextMenuItemExtended", "展開"},
      {"ayu_SettingsContextMenuReactionsPanel", "反應面板 (Reactions)"},
      {"ayu_SettingsContextMenuViewsPanel", "瀏覽數面板 (Views)"},
      {"ayu_SettingsContextMenuTitle", "右鍵選單設定"},
      {"ayu_ViewDeletedMenuText", "查看已刪除"},
      {"ayu_JumpToBeginning", "回到最早"},
      {"ayu_DeleteOwnMessages", "刪除自己的訊息"},
      {"ayu_DeleteOwnMessagesConfirmation", "確定要刪除你在此群組的所有訊息嗎？"},
      {"ayu_DeleteOwnMessagesModeTitle", "刪除自己的訊息"},
      {"ayu_DeleteOwnMessagesModeAll", "刪除全部"},
      {"ayu_DeleteOwnMessagesModeRange", "依時間範圍刪除"},
      {"ayu_DeleteOwnMessagesStartTitle", "刪除自己的訊息 - 開始時間"},
      {"ayu_DeleteOwnMessagesEndTitle", "刪除自己的訊息 - 結束時間"},
      {"ayu_DeleteOwnMessagesStartDesc", "選擇要刪除的起始日期與時間。"},
      {"ayu_DeleteOwnMessagesEndDesc", "選擇要刪除的結束日期與時間。"},
      {"ayu_ContextHideMessage", "隱藏此訊息"},
      {"ayu_UserMessagesMenuText", "查看此用戶訊息"},
      {"ayu_RepeatMenuText", "複讀"},
      {"ayu_RepeatForwardMenuText", "轉傳式複讀"},
      {"ayu_RepeatCopyMenuText", "複製式複讀"},
      {"ayu_MessageDetailsPC", "訊息詳細資訊"},
      {"ayu_RegexFilterQuickAdd", "快速加入過濾器"},
      {"ayu_SettingsContextMenuDescription", "自訂右鍵點選訊息時顯示的項目。"},
      {"ayu_MessageFieldElementsHeader", "輸入欄位圖示"},
      {"ayu_MessageFieldElementAttach", "附件按鈕"},
      {"ayu_MessageFieldElementCommands", "指令按鈕 (/)"},
      {"ayu_MessageFieldElementTTL", "自動刪除按鈕"},
      {"ayu_MessageFieldElementEmoji", "表情符號按鈕"},
      {"ayu_MessageFieldElementVoice", "語音 / 影片訊息按鈕"},
      {"ayu_MessageFieldPopupsHeader", "輸入欄位彈出視窗"},

      // Filters Settings
      {"ayu_CategoryFilters", "過濾器設定"},
      {"ayu_FiltersMenuSelectChat", "選擇對話"},
      {"ayu_FiltersMenuImport", "匯入過濾器"},
      {"ayu_FiltersMenuExport", "匯出過濾器"},
      {"ayu_FiltersMenuClear", "清空過濾器"},
      {"ayu_FiltersClearPopupText", "確定要清空所有的過濾器與排除名單嗎？"},
      {"ayu_FiltersClearPopupActionText", "立即清空"},
      {"ayu_RegexFilters", "正則表達式過濾器"},
      {"ayu_RegexFiltersEnable", "啟用過濾器功能"},
      {"ayu_RegexFiltersEnableSharedInChats", "在對話列表中套用過濾"},
      {"ayu_FiltersHideFromBlocked", "隱藏來自封鎖對象的訊息"},
      {"ayu_RegexFiltersShared", "全域通用過濾器"},
      {"ayu_FiltersShadowBan", "靜默隱藏清單"},
      {"ayu_FiltersQuickShadowBan", "加入靜默隱藏"},
      {"ayu_FiltersQuickUnshadowBan", "取消靜默隱藏"},
      {"ayu_DeleteBypassKeywordsEnable", "啟用關鍵字直接刪除"},
      {"ayu_DeleteBypassKeywordsEdit", "編輯關鍵字清單"},
      {"ayu_DeleteBypassKeywordsPlaceholder", "可用換行、逗號、分號分隔"},
      {"ayu_DeleteBypassKeywordsDescription", "包含這些關鍵字的訊息將被直接刪除，且不保留於防刪紀錄中。"},
      {"ayu_DeleteBypassUserIdsEnable", "啟用指定使用者直接刪除"},
      {"ayu_DeleteBypassUserIdsEdit", "編輯使用者清單"},
      {"ayu_DeleteBypassUserIdsPlaceholder", "可用換行、逗號、分號分隔（僅數字）"},
      {"ayu_DeleteBypassUserIdsDescription", "來自這些使用者的訊息將被直接刪除，且不保留於防刪紀錄中。"},

      // Other
      {"ayu_CategoryOther", "其他設定"},
      {"ayu_SupportHeader", "支持開發者"},
      {"ayu_SupportDescription1", "AyuGram 支援服務"},
      {"ayu_SupportDescription2", "如果您喜歡這個應用程式，可以贊助支持開發，或聯絡 {item}。"},
      {"ayu_CrashReporting", "傳送錯誤報告"},
      {"ayu_CrashReportingDescription", "當程式發生非預期錯誤時，自動傳送匿名報告以協助維護。"},
      {"ayu_RegisterURLScheme", "註冊 URL 協議 (URL Scheme)"},
      {"ayu_ResetSettings", "重置所有設定"},
      {"ayu_ResetSettingsConfirmation", "確定要將所有 AyuGram 設定還原為預設值嗎？"},

      {"ayu_MessageDetailsDatacenterPC", "資料中心"},
      {"ayu_MessageDetailsViewJson", "查看 JSON 資料"},
      {"ayu_ViewJsonSearchPlaceholder", "搜尋鍵名 / 值 / 類型..."},
      {"ayu_ViewJsonDetailPlaceholder", "選取節點以檢視完整值與路徑。"},
      {"ayu_ViewJsonExpandAll", "全部展開"},
      {"ayu_ViewJsonCollapseAll", "全部收合"},
      {"ayu_ViewJsonCopySelectedValue", "複製值"},
      {"ayu_SettingsShowMessageID", "在時間旁顯示訊息 ID"},

      // Experimental Settings
      {"lng_settings_experimental", "實驗性設定"},
      {"lng_settings_experimental_about", "警告！這些是實驗性設定。部分功能可能無法運作，或者導致應用程式崩潰。任何功能都可能在下個版本中無預警移除。使用風險請自行承擔。"},
      {"lng_settings_experimental_restore", "還原預設值"},
      {"lng_settings_experimental_irrelevant", "此選項不適用於您的系統。"},
      {"lng_settings_need_restart", "需要重新啟動才能套用變更。"},
      {"lng_settings_restart_now", "立即重啟"},
      {"lng_settings_restart_later", "稍後"},

      {"forum-hide-chats-list", "論壇模式隱藏對話列表"},
      {"forum-hide-chats-list_desc", "在論壇聊天中，不保留左側窄版對話欄。"},
      {"fractional-scaling", "啟用精準介面縮放"},
      {"fractional-scaling-enabled", "啟用精準介面縮放"},
      {"fractional-scaling-enabled_desc", "嚴格依照系統縮放比例（如 125% / 150%）渲染介面，不做取整。"},
      {"view-profile-in-chats-list-context-menu", "在對話列表右鍵加入「查看個人資料」"},
      {"view-profile-in-chats-list-context-menu_desc", "可在左側對話列表直接右鍵開啟使用者個人資料。"},
      {"show-peer-id-below-about", "在簡介下方顯示 Peer ID"},
      {"show-peer-id-below-about_desc", "在個人簡介區塊下方顯示 API 回傳的 Peer ID。"},
      {"show-channel-joined-below-about", "在簡介下方顯示加入日期"},
      {"show-channel-joined-below-about_desc", "顯示你加入該群組/頻道的時間；可能因權限或 API 限制而無法取得。"},
      {"use-small-msg-bubble-radius", "使用小圓角訊息氣泡"},
      {"use-small-msg-bubble-radius_desc", "讓多數訊息氣泡更接近方形，整體聊天視覺更俐落。"},
      {"disable-autoplay-next", "停用連續自動播放下一則媒體"},
      {"disable-autoplay-next_desc", "停止音訊/語音/影片訊息播完後自動跳到下一則。"},
      {"send-large-photos", "提高壓縮圖片尺寸上限"},
      {"send-large-photos_desc", "仍為壓縮圖片，但最長邊可提高到 2560px。"},
      {"webview-debug-enabled", "啟用 WebView 檢查工具"},
      {"webview-debug-enabled_desc", "可在 WebView 視窗右鍵開啟 Inspect（macOS 請在 Safari 的 Develop 選單開啟）。"},
      {"webview-legacy-edge", "強制使用舊版 Edge WebView"},
      {"webview-legacy-edge_desc", "在 Windows 略過 CoreWebView2，改用舊版 Edge WebView。"},
      {"auto-scroll-inactive-chat", "背景視窗也自動已讀並捲動"},
      {"auto-scroll-inactive-chat_desc", "即使視窗未聚焦，收到新訊息時仍會自動捲動並觸發已讀。"},
      {"hide-reply-button", "隱藏通知中的回覆按鈕"},
      {"hide-reply-button_desc", "移除系統通知上的快速回覆按鈕。"},
      {"custom-notification", "允許停用原生通知"},
      {"custom-notification_desc", "即使平台預設強制原生通知，也允許改用客製通知。"},
      {"gnotification", "強制使用 GNotification"},
      {"gnotification_desc", "在 Linux/GLib 環境強制使用 GNotification；關閉時改為自動偵測。"},
      {"freetype", "改用 FreeType 字型引擎"},
      {"freetype_desc", "以 FreeType 取代系統字型引擎（Windows/macOS）。"},
      {"skip-url-scheme-register", "更新時跳過 tg:// 協定重註冊"},
      {"skip-url-scheme-register_desc", "自動更新後不重新註冊 tg:// URL 協定。"},
      {"external-video-player", "改用系統播放器開啟影片"},
      {"external-video-player_desc", "訊息內不再內嵌播放影片，改由系統預設播放器開啟。"},
      {"new-windows-size-as-first", "新聊天視窗沿用主視窗大小"},
      {"new-windows-size-as-first_desc", "新開聊天視窗時，視窗大小比照目前主視窗。"},
      {"prefer-ipv6", "優先使用 IPv6 連線"},
      {"prefer-ipv6_desc", "在可用時優先走 IPv6（需同時啟用「透過 IPv6 連線」）。"},
      {"fast-buttons-mode", "快速按鈕模式（1-9）"},
      {"fast-buttons-mode_desc", "可用鍵盤數字 1-9 直接觸發訊息下方的內嵌按鈕。"},
      {"touchbar-disabled", "停用 Touch Bar（macOS）"},
      {"touchbar-disabled_desc", "在 macOS 停用 Touch Bar 整合功能。"},
      {"alternative-scroll-processing", "個人資料頁改用舊版捲動邏輯"},
      {"alternative-scroll-processing_desc", "對個人資料頁套用舊版捲動處理，改善特定裝置的捲動問題。"},
      // Specific to Sidebar
      {"ayu_CategoryAyuGram", "AyuGram 設定"},
      {"ayu_CategoriesHeader", "分類清單"},
      {"ayu_LinksHeader", "相關連結"},
      {"ayu_WebviewHeader", "內建網頁設定 (WebView)"},
    };


    const auto lang = Lang::Id().toLower();
    // Only apply Traditional Chinese (Taiwan/HK) translations.
    // We check for "hant" (Traditional) or "tw/hk" specifically to avoid affecting "zh-hans" (Simplified).
    if (lang.contains(qsl("hant")) || lang.contains(qsl("tw")) || lang.contains(qsl("hk"))) {
      if (dict.contains(key)) {
        return dict.value(key);
      }
    }
    return fallback;
  }

} // namespace

#define AYU_T(key) (tr::key() | rpl::map([=](const QString &v) { return AyuHantHelper(qsl(#key), v); }))
#define AYU_S(key) AyuHantHelper(qsl(#key), tr::key(tr::now))
